Add boolean operations (and where_to soon)
coreylowman/dfdx pull request #415
Opened 2023-01-29 01:33 UTC by nkoppel

Implements `and`, `or`, `xor`, and `not` for Tensors. In the process, however, I expanded the definition of OnesTensor and OneFillTensor to all implementors of Unit, which caused Cpu and Cuda to implement Device for all implementors of Unit. Because of this, we now have to specify tensors' dtypes more often.

2023-01-30 20:46 UTC, coreylowman commented
Looking great on first read through - probably going to need a couple more days with this one 😀

2023-02-01 14:30 UTC, coreylowman requested changes
this is looking great! I really like the choose method, great idea! Added a few structural comments, but definitely getting close on this one, thanks for the work!

2023-02-01 14:30 UTC, coreylowman commented on src/tensor_ops/boolean/mod.rs
> +                    .upgrade(self.device.$method2(&self.storage, &rhs.storage).unwrap())
Related to #420, but all of these need to assert that the shapes are equal for runtime shapes. `assert_eq!(self.shape(), rhs.shape()`

2023-02-01 14:30 UTC, coreylowman commented on src/tensor_ops/choose/mod.rs
> +        let (lhs, tape) = lhs.split_tape();
Similar to other comment, but need to add an assert for shape equality for both pairs:
```rust
assert_eq!(self.shape(), lhs.shape());
assert_eq!(self.shape(), rhs.shape());
```

2023-02-01 14:30 UTC, coreylowman commented on src/tensor_ops/choose/mod.rs
> +pub trait ChooseFrom<Lhs, Rhs>: HasErr {
Our first trinary operation! 😀

2023-02-01 14:30 UTC, coreylowman commented on src/tensor_ops/boolean/cuda_kernels.rs
> +        let mut storage = self.dev.take_async(std::vec![false; numel])?;
Ah so this is where we need the ValidAsZeroBits? Can you add a todo comment in here, and then after we merge this we can open an issue to track it

2023-02-01 14:30 UTC, coreylowman commented on src/tensor_ops/boolean/cuda_kernels.rs
> +const MODULE_NAME: &str = "/boolean.ptx";
nitpick for consistency
```suggestion
const MODULE_NAME: &str = "boolean";
```

2023-02-01 14:30 UTC, coreylowman commented on src/tensor_ops/boolean/cuda_kernels.rs
> +        let mut storage = self.dev.take_async(std::vec![false; numel])?;
Same thing with a TODO comment here

2023-02-01 14:30 UTC, coreylowman commented on src/tensor_ops/boolean/mod.rs
> +        }
I think all three of these scalar methods can be removed from this trait and implemented directly in the macro below (or separately). There's weirdness in using tensor methods, unwrapping them for the storage, and then re-wrapping them in the traits down below.

2023-02-01 20:09 UTC, nkoppel commented on src/tensor_ops/boolean/mod.rs
> +    ($op:ident, $method1:ident, $method2:ident, $method3:ident) => {
I've tweaked your suggestions here a little, but I've made these macro parameters have more distinct names.

2023-02-02 14:31 UTC, merged

2023-02-02 14:32 UTC, coreylowman commented
Thanks for the contribution! 🚀